# Generated by Django 4.1.3 on 2022-11-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Owner of League'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
