# Generated by Django 4.1.3 on 2022-11-15 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_planner', '0003_alter_league_name_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Owner of League'),
        ),
    ]
