# Generated by Django 4.1.3 on 2022-11-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0004_alter_league_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="league",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="team",
            name="city",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
