# Generated by Django 4.1.3 on 2022-12-03 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("league_planner", "0008_alter_match_host_alter_match_visitor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "matches"},
        ),
    ]
