# Generated by Django 4.1.3 on 2022-11-15 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_planner.league', verbose_name='Team belong to that League')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_score', models.IntegerField(null=True, verbose_name='Score of host Team')),
                ('visitor_score', models.IntegerField(null=True, verbose_name='Score of visitor Team')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Place where match is played')),
                ('datetime', models.DateTimeField(null=True, verbose_name='Time when match is played')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='league_planner.team', verbose_name='Host Team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_planner.league', verbose_name='Match belong to that League')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='league_planner.team', verbose_name='Visitor Team')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='league_planner.user', verbose_name='Owner of League'),
        ),
    ]
